### ISSUE TITLE
Integrate automatic wrapping of native tokens

### ISSUE THREAD

**Issue by rossneilson** [cryptonative-ch/aqua-interface#403]
A suggestion by Geronimo is to integrate Gnosis Proxy Kit into the UI to allow automatic wrapping of native assets to be used in sales
https://docs.gnosis.io/safe/docs/sdks_cpk/

This could potentially be a great UI feature (allowing for combined values of wrapped+native assets) as well as negating the need of SC issue [#103](https://github.com/cryptonative-ch/mesa-smartcontracts/issues/103) if it is a simpler solution.

**Comment by hhamud** [comment]
can also be incorporated here. #404
